input {
    jdbc {
        jdbc_driver_library    => "/usr/share/logstash/logstash-core/lib/jars/ojdbc8.jar"
        jdbc_driver_class      => "Java::oracle.jdbc.driver.OracleDriver"
        jdbc_connection_string => "jdbc:oracle:thin:@<DBHost>:1521/UATCON"   //Replace DB host
        jdbc_user              => "${oracle_uat_audit_user}"
        jdbc_password          => "${oracle_uat_audit_password}"
        statement              => "SELECT entry_id, action_name, additional_info, audit_type, dbusername, object_name, os_username, event_timestamp, event_t
imestamp_utc, sql_text, userhost, role, return_code, client_program_name, authentication_type FROM CDB_UNIFIED_AUDIT_TRAIL WHERE event_timestamp > :sql_last
_value AND event_timestamp <= SYSTIMESTAMP - INTERVAL '30' SECOND ORDER BY event_timestamp ASC"
        use_column_value       => true
        tracking_column        => "event_timestamp"
        tracking_column_type   => "timestamp"
        schedule               => "*/2 * * * *"
        jdbc_default_timezone  => "Asia/Dubai"
        last_run_metadata_path => "/var/lib/logstash/logstash_last_run/<DBHost>_last_run"     //Replace DB Host
        record_last_run        => true
        clean_run              => false
        add_field => { "oracle_server" => "<DBHost>" }
    }
}

output {
    file {
        path      => "/var/log/logstash/oraclelogs/%{oracle_server}/%{oracle_server}_%{+YYYY.MM.dd}_audit.json"
        codec     => json_lines
        file_mode => 0640
    }
}
